from __future__ import annotations

from enum import StrEnum


class CaseStatus(StrEnum):
    NEW = "NEW"
    TRIAGING = "TRIAGING"
    COLLECTING = "COLLECTING"
    ANALYZING = "ANALYZING"
    NEED_MORE_EVIDENCE = "NEED_MORE_EVIDENCE"
    WAITING_USER = "WAITING_USER"
    DIAGNOSED = "DIAGNOSED"
    ROOT_CAUSE_CONFIRMED = "ROOT_CAUSE_CONFIRMED"
    RESOLVING = "RESOLVING"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    FAILED = "FAILED"


class CaseEvent(StrEnum):
    TRIAGE_STARTED = "TRIAGE_STARTED"
    COLLECTION_STARTED = "COLLECTION_STARTED"
    COLLECTION_COMPLETED = "COLLECTION_COMPLETED"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    EVIDENCE_REQUIRED = "EVIDENCE_REQUIRED"
    USER_ACTION_REQUIRED = "USER_ACTION_REQUIRED"
    DIAGNOSIS_COMPLETED = "DIAGNOSIS_COMPLETED"
    ROOT_CAUSE_CONFIRMED = "ROOT_CAUSE_CONFIRMED"
    RESOLUTION_STARTED = "RESOLUTION_STARTED"
    FIX_VERIFIED = "FIX_VERIFIED"
    FIX_REEVALUATION_REQUIRED = "FIX_REEVALUATION_REQUIRED"
    CASE_CLOSED = "CASE_CLOSED"
    CASE_FAILED = "CASE_FAILED"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    # Diagnosis parent jobs may legitimately wait for evidence/user input.
    WAITING_EVIDENCE = "WAITING_EVIDENCE"
    WAITING_USER = "WAITING_USER"


class RunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    UNAVAILABLE = "UNAVAILABLE"


class DiagnosisRunStatus(StrEnum):
    PENDING = "PENDING"
    ANALYZING = "ANALYZING"
    WAITING_EVIDENCE = "WAITING_EVIDENCE"
    WAITING_USER = "WAITING_USER"
    DIAGNOSED = "DIAGNOSED"
    FAILED = "FAILED"


class CollectionPlanStatus(StrEnum):
    PROPOSED = "PROPOSED"
    EXECUTING = "EXECUTING"
    WAITING_USER = "WAITING_USER"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class RuleVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"
    DISABLED = "DISABLED"


class KnowledgeStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"
    DISABLED = "DISABLED"


class ReportStatus(StrEnum):
    GENERATED = "GENERATED"
    FAILED = "FAILED"


class EvidenceKind(StrEnum):
    RAW = "RAW"
    DERIVED = "DERIVED"


class EvidenceScope(StrEnum):
    CASE = "CASE"
    SESSION = "SESSION"
    ATTEMPT = "ATTEMPT"
    CALL = "CALL"
    STREAM = "STREAM"
    TIME_WINDOW = "TIME_WINDOW"
    DEVICE = "DEVICE"


class EvidenceLevel(StrEnum):
    L1 = "L1"
    L2 = "L2"
    L3 = "L3"
    L4 = "L4"
    L5 = "L5"


class EvidenceCompleteness(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    UNAVAILABLE = "UNAVAILABLE"
    CORRUPTED = "CORRUPTED"
    NOT_REQUIRED = "NOT_REQUIRED"


class FindingStatus(StrEnum):
    DETECTED = "DETECTED"
    NOT_FOUND = "NOT_FOUND"
    UNAVAILABLE = "UNAVAILABLE"
    INCONCLUSIVE = "INCONCLUSIVE"


class HypothesisState(StrEnum):
    OPEN = "OPEN"
    SUPPORTED = "SUPPORTED"
    STRONGLY_SUPPORTED = "STRONGLY_SUPPORTED"
    CONFIRMED = "CONFIRMED"
    CONTRADICTED = "CONTRADICTED"
    REJECTED = "REJECTED"


LEGACY_HYPOTHESIS_STATE_MAP = {
    "PROPOSED": HypothesisState.OPEN,
    "ACTIVE": HypothesisState.OPEN,
    "UNRESOLVED": HypothesisState.OPEN,
    "WEAKENED": HypothesisState.CONTRADICTED,
}


def normalize_hypothesis_state(value: str | HypothesisState) -> HypothesisState:
    if isinstance(value, HypothesisState):
        return value
    raw = str(value).upper()
    if raw in LEGACY_HYPOTHESIS_STATE_MAP:
        return LEGACY_HYPOTHESIS_STATE_MAP[raw]
    return HypothesisState(raw)


class RuleCategory(StrEnum):
    SAFETY = "SAFETY"
    CONFIRM = "CONFIRM"
    CONTRADICTION = "CONTRADICTION"
    SUPPORT = "SUPPORT"
    COLLECTION = "COLLECTION"
    DISPLAY = "DISPLAY"


RULE_CATEGORY_ORDER = {
    RuleCategory.SAFETY: 0,
    RuleCategory.CONFIRM: 1,
    RuleCategory.CONTRADICTION: 2,
    RuleCategory.SUPPORT: 3,
    RuleCategory.COLLECTION: 4,
    RuleCategory.DISPLAY: 5,
}


class ActionRiskLevel(StrEnum):
    L0 = "L0"
    L1 = "L1"
    L2 = "L2"
    L3 = "L3"
    L4 = "L4"


class UserRole(StrEnum):
    VIEWER = "VIEWER"
    ENGINEER = "ENGINEER"
    EXPERT_REVIEWER = "EXPERT_REVIEWER"
    ADMIN = "ADMIN"
    SERVICE = "SERVICE"


class ErrorCategory(StrEnum):
    VALIDATION = "VALIDATION"
    DEVICE = "DEVICE"
    SSH = "SSH"
    VOICE_CONTEXT = "VOICE_CONTEXT"
    ACTION = "ACTION"
    CAPTURE = "CAPTURE"
    PCM = "PCM"
    PACKET = "PACKET"
    ANALYZER = "ANALYZER"
    DIAGNOSIS = "DIAGNOSIS"
    REPRODUCTION = "REPRODUCTION"
    CLEANUP = "CLEANUP"
    STORAGE = "STORAGE"
    AUTH = "AUTH"
    PERMISSION = "PERMISSION"
    INTERNAL = "INTERNAL"


class IdempotencyStatus(StrEnum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class EvidenceRelationType(StrEnum):
    DERIVED_FROM = "DERIVED_FROM"
    SUPERSEDES = "SUPERSEDES"
    REFERENCES = "REFERENCES"


class DependencyPolicy(StrEnum):
    WAIT_ALL_SUCCESS = "WAIT_ALL_SUCCESS"
    WAIT_TERMINAL_ALLOW_PARTIAL = "WAIT_TERMINAL_ALLOW_PARTIAL"
    OPTIONAL = "OPTIONAL"

class ActorType(StrEnum):
    USER = "USER"
    SERVICE = "SERVICE"
    AI = "AI"
    SYSTEM = "SYSTEM"


class PermissionName(StrEnum):
    CASE_READ = "CASE_READ"
    CASE_WRITE = "CASE_WRITE"
    EVIDENCE_READ = "EVIDENCE_READ"
    EVIDENCE_UPLOAD = "EVIDENCE_UPLOAD"
    JOB_READ = "JOB_READ"
    JOB_CONTROL = "JOB_CONTROL"
    DIAGNOSIS_READ = "DIAGNOSIS_READ"
    DIAGNOSIS_RUN = "DIAGNOSIS_RUN"
    RULE_READ = "RULE_READ"
    RULE_EDIT = "RULE_EDIT"
    RULE_APPROVE = "RULE_APPROVE"
    KNOWLEDGE_READ = "KNOWLEDGE_READ"
    KNOWLEDGE_EDIT = "KNOWLEDGE_EDIT"
    KNOWLEDGE_VERIFY = "KNOWLEDGE_VERIFY"
    REPORT_READ = "REPORT_READ"
    REPORT_GENERATE = "REPORT_GENERATE"
    AUDIT_READ = "AUDIT_READ"
    REPRODUCTION_READ = "REPRODUCTION_READ"
    REPRODUCTION_CONTROL = "REPRODUCTION_CONTROL"
    EXPERIMENT_READ = "EXPERIMENT_READ"
    EXPERIMENT_CONTROL = "EXPERIMENT_CONTROL"
    FIX_READ = "FIX_READ"
    FIX_CONTROL = "FIX_CONTROL"
    ADMIN = "ADMIN"


class EventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    CASE_STATE_CHANGED = "CASE_STATE_CHANGED"
    JOB_STATE_CHANGED = "JOB_STATE_CHANGED"
    JOB_DEPENDENCY_CREATED = "JOB_DEPENDENCY_CREATED"
    EVIDENCE_CREATED = "EVIDENCE_CREATED"
    EVIDENCE_UPLOADED = "EVIDENCE_UPLOADED"
    ANALYZER_COMPLETED = "ANALYZER_COMPLETED"
    PACKET_ANALYSIS_FINISHED = "PACKET_ANALYSIS_FINISHED"
    MEDIA_ANALYSIS_FINISHED = "MEDIA_ANALYSIS_FINISHED"
    PCM_ANALYSIS_FINISHED = "PCM_ANALYSIS_FINISHED"
    DIAGNOSIS_STARTED = "DIAGNOSIS_STARTED"
    DIAGNOSIS_CYCLE = "DIAGNOSIS_CYCLE"
    DIAGNOSIS_UPDATED = "DIAGNOSIS_UPDATED"
    HYPOTHESIS_CONFIRMED = "HYPOTHESIS_CONFIRMED"
    REPRODUCTION_CREATED = "REPRODUCTION_CREATED"
    REPRODUCTION_STATE_CHANGED = "REPRODUCTION_STATE_CHANGED"
    REPRODUCTION_ATTEMPT_CHANGED = "REPRODUCTION_ATTEMPT_CHANGED"
    REPRODUCTION_CALL_CHANGED = "REPRODUCTION_CALL_CHANGED"
    REPRODUCTION_ARM_VALIDATED = "REPRODUCTION_ARM_VALIDATED"
    REPRODUCTION_CLEANUP_VALIDATED = "REPRODUCTION_CLEANUP_VALIDATED"
    TARGET_CONFIRMED = "TARGET_CONFIRMED"
    CLEANUP_ALERT = "CLEANUP_ALERT"
    REPORT_READY = "REPORT_READY"
    DIAGNOSIS_REPORT_GENERATED = "DIAGNOSIS_REPORT_GENERATED"
    RULE_VERSION_ACTIVATED = "RULE_VERSION_ACTIVATED"
    KNOWLEDGE_VERIFIED = "KNOWLEDGE_VERIFIED"
    DIAGNOSTIC_QUESTION_CHANGED = "DIAGNOSTIC_QUESTION_CHANGED"
    EXPERIMENT_CREATED = "EXPERIMENT_CREATED"
    EXPERIMENT_RUN_CHANGED = "EXPERIMENT_RUN_CHANGED"
    ENVIRONMENT_COMPARISON_COMPLETED = "ENVIRONMENT_COMPARISON_COMPLETED"
    CAUSAL_ASSESSMENT_UPDATED = "CAUSAL_ASSESSMENT_UPDATED"
    ROOT_CAUSE_CAUSALLY_CONFIRMED = "ROOT_CAUSE_CAUSALLY_CONFIRMED"
    FIX_ACTION_CREATED = "FIX_ACTION_CREATED"
    FIX_VERIFICATION_UPDATED = "FIX_VERIFICATION_UPDATED"


class ReproductionState(StrEnum):
    CREATED = "CREATED"
    AUTO_ARMING = "AUTO_ARMING"
    ARMED = "ARMED"
    WATCHING = "WATCHING"
    ACTIVITY_DETECTED = "ACTIVITY_DETECTED"
    CALL_DETECTED = "CALL_DETECTED"
    CAPTURING = "CAPTURING"
    CALL_END_DETECTED = "CALL_END_DETECTED"
    POST_CAPTURE = "POST_CAPTURE"
    ENHANCING = "ENHANCING"
    WAITING_DEVICE_RESOURCE = "WAITING_DEVICE_RESOURCE"
    WAITING_GLOBAL_RESOURCE = "WAITING_GLOBAL_RESOURCE"
    WAITING_EXTERNAL_ACTION = "WAITING_EXTERNAL_ACTION"
    WATCH_TIMEOUT = "WATCH_TIMEOUT"
    CAPTURE_TIMEOUT = "CAPTURE_TIMEOUT"
    ARM_FAILED = "ARM_FAILED"
    DEVICE_LOST = "DEVICE_LOST"
    ORPHANED = "ORPHANED"
    CLEANUP = "CLEANUP"
    CLEANUP_DEGRADED = "CLEANUP_DEGRADED"
    CLEANUP_FAILED = "CLEANUP_FAILED"
    FINALIZING = "FINALIZING"
    ANALYZING = "ANALYZING"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class ReproductionEvent(StrEnum):
    START_ARMING = "START_ARMING"
    DEVICE_RESOURCE_BUSY = "DEVICE_RESOURCE_BUSY"
    GLOBAL_RESOURCE_BUSY = "GLOBAL_RESOURCE_BUSY"
    ARM_READY = "ARM_READY"
    ARM_FAILED = "ARM_FAILED"
    WATCH_STARTED = "WATCH_STARTED"
    ACTIVITY = "ACTIVITY"
    CALL_BOUND = "CALL_BOUND"
    CAPTURE_STARTED = "CAPTURE_STARTED"
    CALL_ENDED = "CALL_ENDED"
    POST_CAPTURE_STARTED = "POST_CAPTURE_STARTED"
    WATCH_TIMEOUT = "WATCH_TIMEOUT"
    CAPTURE_TIMEOUT = "CAPTURE_TIMEOUT"
    DEVICE_LOST = "DEVICE_LOST"
    LEASE_EXPIRED = "LEASE_EXPIRED"
    ENHANCEMENT_STARTED = "ENHANCEMENT_STARTED"
    ENHANCEMENT_ARMED = "ENHANCEMENT_ARMED"
    EXTERNAL_ACTION_REQUIRED = "EXTERNAL_ACTION_REQUIRED"
    RESOURCE_AVAILABLE = "RESOURCE_AVAILABLE"
    CLEANUP_STARTED = "CLEANUP_STARTED"
    CLEANUP_VERIFIED = "CLEANUP_VERIFIED"
    CLEANUP_VERIFIED_EXTERNAL_WAIT = "CLEANUP_VERIFIED_EXTERNAL_WAIT"
    CAPTURE_RECOVERY_STARTED = "CAPTURE_RECOVERY_STARTED"
    CLEANUP_DEGRADED = "CLEANUP_DEGRADED"
    CLEANUP_FAILED = "CLEANUP_FAILED"
    FINALIZE_STARTED = "FINALIZE_STARTED"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    SESSION_COMPLETED = "SESSION_COMPLETED"
    SESSION_PARTIAL = "SESSION_PARTIAL"
    SESSION_FAILED = "SESSION_FAILED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"


class ReproductionProfileStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEW = "REVIEW"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"
    DISABLED = "DISABLED"


class CaptureStage(StrEnum):
    BASE = "BASE"
    ENHANCED = "ENHANCED"
    DEEP = "DEEP"


class EndPolicy(StrEnum):
    FIRST_TARGET = "FIRST_TARGET"
    EVIDENCE_SUFFICIENCY = "EVIDENCE_SUFFICIENCY"
    TARGET_COUNT = "TARGET_COUNT"
    CONTROL_TARGET_PAIR = "CONTROL_TARGET_PAIR"
    SESSION_WINDOW = "SESSION_WINDOW"


class AttemptStatus(StrEnum):
    ACTIVE = "ACTIVE"
    VALID = "VALID"
    INVALID = "INVALID"
    COMPLETED = "COMPLETED"
    ABORTED = "ABORTED"


class CallVerdict(StrEnum):
    MATCH = "MATCH"
    NO_MATCH = "NO_MATCH"
    INCONCLUSIVE = "INCONCLUSIVE"


class CallRole(StrEnum):
    CONTROL = "CONTROL"
    TARGET = "TARGET"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNRELATED = "UNRELATED"


class CaptureChannel(StrEnum):
    PCAP = "PCAP"
    PCM_RX = "PCM_RX"
    PCM_TX = "PCM_TX"
    DEBUG = "DEBUG"
    LOG = "LOG"


class ChannelHealth(StrEnum):
    UNKNOWN = "UNKNOWN"
    STARTING = "STARTING"
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    STOPPED = "STOPPED"
    FAILED = "FAILED"


class ArmValidationStatus(StrEnum):
    PENDING = "PENDING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"


class CleanupStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED = "REQUIRED"
    RUNNING = "RUNNING"
    CLEANUP_VERIFIED = "CLEANUP_VERIFIED"
    CLEANUP_VERIFIED_EXTERNAL_WAIT = "CLEANUP_VERIFIED_EXTERNAL_WAIT"
    CAPTURE_RECOVERY_STARTED = "CAPTURE_RECOVERY_STARTED"
    CLEANUP_DEGRADED = "CLEANUP_DEGRADED"
    CLEANUP_FAILED = "CLEANUP_FAILED"


class EvidenceSufficiency(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    SUFFICIENT = "SUFFICIENT"
    INSUFFICIENT_RETRY = "INSUFFICIENT_RETRY"
    INSUFFICIENT_ENHANCE = "INSUFFICIENT_ENHANCE"
    INSUFFICIENT_CAPTURE_RECOVERY = "INSUFFICIENT_CAPTURE_RECOVERY"
    INSUFFICIENT_EXTERNAL_ACTION = "INSUFFICIENT_EXTERNAL_ACTION"


class EvidenceGapAction(StrEnum):
    RETRY_SAME_CAPTURE = "RETRY_SAME_CAPTURE"
    ENHANCE_CAPTURE = "ENHANCE_CAPTURE"
    CAPTURE_RECOVERY = "CAPTURE_RECOVERY"
    EXTERNAL_ACTION_REQUIRED = "EXTERNAL_ACTION_REQUIRED"
    NONE = "NONE"


class DiagnosticQuestionState(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    ANSWERED = "ANSWERED"
    BLOCKED = "BLOCKED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class CleanupRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    VERIFIED = "VERIFIED"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"


class LockStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"
    EXPIRED = "EXPIRED"


class ReproductionCallStatus(StrEnum):
    ACTIVE = "ACTIVE"
    ENDED = "ENDED"
    ANALYZING = "ANALYZING"
    ANALYZED = "ANALYZED"


class AnchorType(StrEnum):
    PRIMARY_START = "PRIMARY_START"
    CALL_BINDING = "CALL_BINDING"
    MEDIA_BINDING = "MEDIA_BINDING"
    PRIMARY_END = "PRIMARY_END"
    SECONDARY_END = "SECONDARY_END"
    FALLBACK_END = "FALLBACK_END"
    LIVE_ANOMALY = "LIVE_ANOMALY"
    RECONSTRUCTED_START = "RECONSTRUCTED_START"


class TimestampSource(StrEnum):
    COLLECTOR_MONOTONIC = "COLLECTOR_MONOTONIC"
    COLLECTOR_WALL = "COLLECTOR_WALL"
    DEVICE_WALL = "DEVICE_WALL"
    DEVICE_UPTIME = "DEVICE_UPTIME"
    PCAP = "PCAP"
    COLLECTOR_RECEIVE = "COLLECTOR_RECEIVE"


class CaptureSegmentStatus(StrEnum):
    ACTIVE = "ACTIVE"
    FROZEN = "FROZEN"
    RETAINED = "RETAINED"
    EVICTED = "EVICTED"
    FINALIZED = "FINALIZED"
    CORRUPTED = "CORRUPTED"


class RetentionClass(StrEnum):
    TEMP_RING = "TEMP_RING"
    SHORT_ATTEMPT = "SHORT_ATTEMPT"
    PERMANENT_RAW = "PERMANENT_RAW"
    PERMANENT_DERIVED = "PERMANENT_DERIVED"
    REGENERATABLE = "REGENERATABLE"
    TEMP_STAGING = "TEMP_STAGING"


class EvidenceFinalizeStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"


class AnalyzerMode(StrEnum):
    LIVE = "LIVE"
    CALL_QUICK = "CALL_QUICK"
    FULL = "FULL"


class DiagnosticQuestionLevel(StrEnum):
    SYMPTOM_CONFIRM = "SYMPTOM_CONFIRM"
    FAULT_DOMAIN = "FAULT_DOMAIN"
    FAULT_LAYER = "FAULT_LAYER"
    ROOT_CAUSE = "ROOT_CAUSE"
    FIX_VERIFICATION = "FIX_VERIFICATION"


class ExperimentState(StrEnum):
    CREATED = "CREATED"
    WAITING_EXTERNAL_ACTION = "WAITING_EXTERNAL_ACTION"
    IN_PROGRESS = "IN_PROGRESS"
    EVALUATING = "EVALUATING"
    STRONGLY_SUPPORTED = "STRONGLY_SUPPORTED"
    ROOT_CAUSE_CONFIRMED = "ROOT_CAUSE_CONFIRMED"
    NOT_COMPARABLE = "NOT_COMPARABLE"
    INCONCLUSIVE = "INCONCLUSIVE"
    CONTRADICTED = "CONTRADICTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ExperimentRunStatus(StrEnum):
    PLANNED = "PLANNED"
    WAITING_EXTERNAL_ACTION = "WAITING_EXTERNAL_ACTION"
    READY = "READY"
    REPRODUCING = "REPRODUCING"
    COMPLETED = "COMPLETED"
    INVALID = "INVALID"
    FAILED = "FAILED"


class ExperimentVariant(StrEnum):
    A1 = "A1"
    B = "B"
    A2 = "A2"
    REPEAT = "REPEAT"


class ConfirmationPolicy(StrEnum):
    AB_SUFFICIENT = "AB_SUFFICIENT"
    ABA_PREFERRED = "ABA_PREFERRED"
    ABA_REQUIRED = "ABA_REQUIRED"
    REPEAT_MATCH = "REPEAT_MATCH"
    DIRECT_EVIDENCE = "DIRECT_EVIDENCE"


class EnvironmentComparisonStatus(StrEnum):
    COMPARABLE = "COMPARABLE"
    COMPARABLE_WITH_SOFT_DRIFT = "COMPARABLE_WITH_SOFT_DRIFT"
    NOT_COMPARABLE = "NOT_COMPARABLE"


class DriftClassification(StrEnum):
    EXPECTED_CHANGE = "EXPECTED_CHANGE"
    SOFT_DRIFT = "SOFT_DRIFT"
    HARD_DRIFT = "HARD_DRIFT"


class CausalConclusionState(StrEnum):
    HYPOTHESIS = "HYPOTHESIS"
    SUPPORTED = "SUPPORTED"
    STRONGLY_SUPPORTED = "STRONGLY_SUPPORTED"
    ROOT_CAUSE_CONFIRMED = "ROOT_CAUSE_CONFIRMED"
    CONTRADICTED = "CONTRADICTED"
    NOT_COMPARABLE = "NOT_COMPARABLE"
    INCONCLUSIVE = "INCONCLUSIVE"


class FixActionType(StrEnum):
    SOFTWARE_PATCH = "SOFTWARE_PATCH"
    CONFIG_CHANGE = "CONFIG_CHANGE"
    PHONE_REPLACE = "PHONE_REPLACE"
    LINE_REPLACE = "LINE_REPLACE"
    POWER_SUPPLY_REPLACE = "POWER_SUPPLY_REPLACE"
    FXS_PORT_CHANGE = "FXS_PORT_CHANGE"
    DEVICE_REPLACE = "DEVICE_REPLACE"
    REBOOT = "REBOOT"
    OTHER = "OTHER"


class FixVerificationStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    FIX_VERIFIED = "FIX_VERIFIED"
    FIX_FAILED = "FIX_FAILED"
    FIX_REGRESSION = "FIX_REGRESSION"
    FIX_INCONCLUSIVE = "FIX_INCONCLUSIVE"


class FixVerificationRunStatus(StrEnum):
    PLANNED = "PLANNED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
