from __future__ import annotations

from enum import StrEnum


class CaptureSessionState(StrEnum):
    CREATED = "CREATED"
    ACQUIRING_LEASE = "ACQUIRING_LEASE"
    RECOVERING = "RECOVERING"
    PREPARING = "PREPARING"
    CAPTURE_PATH_READY = "CAPTURE_PATH_READY"
    WATCHING = "WATCHING"
    TARGET_CONFIRMED = "TARGET_CONFIRMED"
    POST_TARGET_OBSERVATION = "POST_TARGET_OBSERVATION"
    EVIDENCE_DRAINING = "EVIDENCE_DRAINING"
    COVERAGE_FINALIZING = "COVERAGE_FINALIZING"
    CLEANUP = "CLEANUP"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class CaptureHealth(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"


class CaptureLeaseState(StrEnum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    FENCED = "FENCED"
    RELEASING = "RELEASING"
    RELEASED = "RELEASED"


class CaptureEpochState(StrEnum):
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    ENDED = "ENDED"
    FAILED = "FAILED"


class RecoveryClassification(StrEnum):
    CLEAN = "CLEAN"
    SAME_SESSION_ALIVE = "SAME_SESSION_ALIVE"
    SAME_SESSION_DEAD = "SAME_SESSION_DEAD"
    OLD_SESSION_ALIVE = "OLD_SESSION_ALIVE"
    MULTIPLE_PRODUCERS = "MULTIPLE_PRODUCERS"
    DUT_REBOOT = "DUT_REBOOT"


class RecoveryResultStatus(StrEnum):
    CLEAN = "CLEAN"
    ADOPTED = "ADOPTED"
    REPAIRED = "REPAIRED"
    CONFLICT_RESOLVED = "CONFLICT_RESOLVED"
    FAILED = "FAILED"


class ChannelRequirement(StrEnum):
    REQUIRED = "REQUIRED"
    CONDITIONAL_REQUIRED = "CONDITIONAL_REQUIRED"
    OPTIONAL = "OPTIONAL"


class GapCertainty(StrEnum):
    CONFIRMED = "CONFIRMED"
    POSSIBLE = "POSSIBLE"


class CaptureEventType(StrEnum):
    CAPTURE_SESSION_CREATED = "CAPTURE_SESSION_CREATED"
    CAPTURE_LEASE_ACQUIRED = "CAPTURE_LEASE_ACQUIRED"
    CAPTURE_LEASE_RENEWED = "CAPTURE_LEASE_RENEWED"
    CAPTURE_LEASE_RELEASED = "CAPTURE_LEASE_RELEASED"
    CAPTURE_LEASE_FENCED = "CAPTURE_LEASE_FENCED"
    DUT_FENCE_PUBLISHED = "DUT_FENCE_PUBLISHED"
    RECOVERY_STARTED = "RECOVERY_STARTED"
    RECOVERY_CLASSIFIED = "RECOVERY_CLASSIFIED"
    RECOVERY_ADOPTED = "RECOVERY_ADOPTED"
    RECOVERY_ORPHAN_FOUND = "RECOVERY_ORPHAN_FOUND"
    RECOVERY_CONFLICT_FOUND = "RECOVERY_CONFLICT_FOUND"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    CAPTURE_EPOCH_STARTED = "CAPTURE_EPOCH_STARTED"
    PRODUCER_STARTING = "PRODUCER_STARTING"
    PRODUCER_READY = "PRODUCER_READY"
    PRODUCER_STOPPED = "PRODUCER_STOPPED"
    PRODUCER_DIED = "PRODUCER_DIED"
    DUT_REBOOT_DETECTED = "DUT_REBOOT_DETECTED"
    CAPTURE_GAP_START = "CAPTURE_GAP_START"
    CAPTURE_GAP_END = "CAPTURE_GAP_END"


class CaptureAttemptState(StrEnum):
    PROVISIONAL = "PROVISIONAL"
    CONFIRMED = "CONFIRMED"
    DATA_PLANE_VERIFYING = "DATA_PLANE_VERIFYING"
    ENDED = "ENDED"
    EVIDENCE_FINALIZING = "EVIDENCE_FINALIZING"
    EVALUATED = "EVALUATED"
    CLASSIFIED_GLITCH = "CLASSIFIED_GLITCH"


class AttemptClassification(StrEnum):
    NORMAL = "NORMAL"
    FXS_HOOK_GLITCH = "FXS_HOOK_GLITCH"
    FALLBACK_ANCHORED = "FALLBACK_ANCHORED"


class ReadinessStage(StrEnum):
    CAPTURE_PATH_READY = "CAPTURE_PATH_READY"
    DATA_PLANE_VERIFIED = "DATA_PLANE_VERIFIED"


class ReadinessStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    DEGRADED = "DEGRADED"
    REVOKED = "REVOKED"
    FAILED = "FAILED"


class VerificationStatus(StrEnum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    DEGRADED = "DEGRADED"
    MISSING = "MISSING"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class CoverageStatus(StrEnum):
    PENDING = "PENDING"
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class CoverageIntervalType(StrEnum):
    COVERED = "COVERED"
    GAP = "GAP"
    UNKNOWN = "UNKNOWN"


class CaptureCompleteness(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class SignalAvailabilityStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE_NOT_CAPTURED = "UNAVAILABLE_NOT_CAPTURED"
    UNAVAILABLE_ENCRYPTED = "UNAVAILABLE_ENCRYPTED"
    UNAVAILABLE_NOT_APPLICABLE = "UNAVAILABLE_NOT_APPLICABLE"
    DEGRADED = "DEGRADED"
    UNKNOWN = "UNKNOWN"


class DiagnosticConfidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"
