from __future__ import annotations

# Abstract actions only. EC-02 maps these IDs to real DUT commands later.
# Phase C mock platform implements these actions without executing shell/AIM.
REPRODUCTION_ACTION_IDS = frozenset({
    'RESOLVE_VOICE_RUNTIME_CONTEXT',
    'CAPTURE_PRE_SNAPSHOT',
    'START_VOICE_PCAP',
    'START_PCM_RX',
    'START_PCM_TX',
    'ENABLE_BASIC_VOIP_DEBUG',
    'ENABLE_DTMF_DEBUG',
    'ENABLE_DSP_DEBUG',
    'ENABLE_SIP_PACKET_LOG',
    'STOP_PCM_RX',
    'STOP_PCM_TX',
    'DISABLE_BASIC_VOIP_DEBUG',
    'DISABLE_DTMF_DEBUG',
    'DISABLE_DSP_DEBUG',
    'DISABLE_SIP_PACKET_LOG',
    'CAPTURE_POST_SNAPSHOT',
    'STOP_VOICE_PCAP',
})

SAFE_AUTO_ARM_ACTION_IDS = frozenset({
    'CAPTURE_PRE_SNAPSHOT',
    'START_VOICE_PCAP',
    'START_PCM_RX',
    'START_PCM_TX',
    'ENABLE_BASIC_VOIP_DEBUG',
    'ENABLE_DTMF_DEBUG',
    'ENABLE_DSP_DEBUG',
    'ENABLE_SIP_PACKET_LOG',
})

CLEANUP_ACTION_IDS = frozenset({
    'STOP_PCM_RX', 'STOP_PCM_TX',
    'DISABLE_BASIC_VOIP_DEBUG', 'DISABLE_DTMF_DEBUG', 'DISABLE_DSP_DEBUG', 'DISABLE_SIP_PACKET_LOG',
    'CAPTURE_POST_SNAPSHOT', 'STOP_VOICE_PCAP',
})

ACTION_CLEANUP_PAIR = {
    'START_PCM_RX': 'STOP_PCM_RX',
    'START_PCM_TX': 'STOP_PCM_TX',
    'ENABLE_BASIC_VOIP_DEBUG': 'DISABLE_BASIC_VOIP_DEBUG',
    'ENABLE_DTMF_DEBUG': 'DISABLE_DTMF_DEBUG',
    'ENABLE_DSP_DEBUG': 'DISABLE_DSP_DEBUG',
    'ENABLE_SIP_PACKET_LOG': 'DISABLE_SIP_PACKET_LOG',
    'START_VOICE_PCAP': 'STOP_VOICE_PCAP',
}
